
    create table form_responses (
        id bigint generated by default as identity,
        data TEXT not null,
        event_code varchar(255) not null,
        match_code varchar(255),
        response_type varchar(255) not null check (response_type in ('QUALITATIVE_MATCH','QUANTITATIVE_MATCH','PIT')),
        submitted_at timestamp(6) with time zone not null,
        team_number bigint not null,
        form_id bigint not null,
        form_version_id bigint not null,
        primary key (id)
    );

    create table form_versions (
        id bigint generated by default as identity,
        schema TEXT not null,
        version integer not null,
        form_id bigint not null,
        primary key (id)
    );

    create table forms (
        id bigint generated by default as identity,
        created_at timestamp(6) with time zone,
        type varchar(255) not null check (type in ('QUALITATIVE_MATCH','QUANTITATIVE_MATCH','PIT')),
        updated_at timestamp(6) with time zone not null,
        version integer,
        primary key (id),
        unique (type)
    );

    create table settings (
        id bigint not null,
        eventCode varchar(255) not null unique,
        primary key (id)
    );

    create table team (
        id bigint generated by default as identity,
        created_at timestamp(6) with time zone not null,
        nickname varchar(255) not null,
        picture_url varchar(255),
        team_number integer not null,
        updated_at timestamp(6) with time zone not null,
        primary key (id)
    );

    alter table if exists form_responses 
       add constraint FKfbepy10fuom3c3u41cr547u7d 
       foreign key (form_id) 
       references forms;

    alter table if exists form_responses 
       add constraint FKbh4l96wjcx9q2bfh3hb1ewaej 
       foreign key (form_version_id) 
       references form_versions;

    alter table if exists form_versions 
       add constraint FKjsugk8f29jo2k0sw4fpflwyc2 
       foreign key (form_id) 
       references forms;
