-- sql
CREATE TABLE assignments (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                             assignment_type VARCHAR(255) NOT NULL CHECK (assignment_type IN ('QUALITATIVE_MATCH','QUANTITATIVE_MATCH','PIT')),
                             scouter_id VARCHAR(255) NOT NULL,
                             event_code VARCHAR(255) NOT NULL,
                             match_id VARCHAR(255),
                             team_number BIGINT,
                             CONSTRAINT pk_assignments PRIMARY KEY (id)
);

CREATE TABLE teams (
                       number BIGINT NOT NULL,
                       name VARCHAR(255) NOT NULL,
                       CONSTRAINT pk_teams PRIMARY KEY (number)
);

CREATE TABLE events (
                        code VARCHAR(255) NOT NULL,
                        name VARCHAR(255) NOT NULL,
                        start_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                        end_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                        CONSTRAINT pk_events PRIMARY KEY (code)
);

CREATE TABLE event_teams (
                             event_code VARCHAR(255) NOT NULL,
                             team_number BIGINT NOT NULL
);

CREATE TABLE forms (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       type VARCHAR(255) NOT NULL CHECK (type IN ('QUALITATIVE_MATCH','QUANTITATIVE_MATCH','PIT')),
                       version INTEGER,
                       created_at TIMESTAMP(6) WITH TIME ZONE,
                       updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                       CONSTRAINT pk_forms PRIMARY KEY (id),
                       CONSTRAINT uc_forms_type UNIQUE (type)
);

CREATE TABLE form_versions (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                               form_id BIGINT NOT NULL,
                               version INTEGER NOT NULL,
                               schema TEXT NOT NULL,
                               CONSTRAINT pk_form_versions PRIMARY KEY (id)
);

CREATE TABLE form_responses (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                data TEXT NOT NULL,
                                event_code VARCHAR(255) NOT NULL,
                                match_code VARCHAR(255),
                                response_type VARCHAR(255) NOT NULL CHECK (response_type IN ('QUALITATIVE_MATCH','QUANTITATIVE_MATCH','PIT')),
                                submitted_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                                team_number BIGINT NOT NULL,
                                form_id BIGINT NOT NULL,
                                form_version_id BIGINT NOT NULL,
                                CONSTRAINT pk_form_responses PRIMARY KEY (id)
);

CREATE TABLE matches (
                         code VARCHAR(255) NOT NULL,
                         start_time TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                         blue_one BIGINT NOT NULL,
                         blue_two BIGINT NOT NULL,
                         blue_three BIGINT NOT NULL,
                         event_code VARCHAR(255) NOT NULL,
                         red_one BIGINT NOT NULL,
                         red_two BIGINT NOT NULL,
                         red_three BIGINT NOT NULL,
                         CONSTRAINT pk_matches PRIMARY KEY (code)
);

CREATE TABLE settings (
                          id BIGINT NOT NULL,
                          event_code VARCHAR(255) NOT NULL,
                          CONSTRAINT pk_settings PRIMARY KEY (id),
                          CONSTRAINT uc_settings_eventcode UNIQUE (event_code)
);

-- Foreign keys
ALTER TABLE assignments
    ADD CONSTRAINT fk_assignments_event FOREIGN KEY (event_code) REFERENCES events (code),
    ADD CONSTRAINT fk_assignments_match FOREIGN KEY (match_id) REFERENCES matches (code),
    ADD CONSTRAINT fk_assignments_team FOREIGN KEY (team_number) REFERENCES teams (number);

ALTER TABLE event_teams
    ADD CONSTRAINT fk_event_teams_event FOREIGN KEY (event_code) REFERENCES events (code),
    ADD CONSTRAINT fk_event_teams_team FOREIGN KEY (team_number) REFERENCES teams (number);

ALTER TABLE form_versions
    ADD CONSTRAINT fk_form_versions_form FOREIGN KEY (form_id) REFERENCES forms (id);

ALTER TABLE form_responses
    ADD CONSTRAINT fk_form_responses_form FOREIGN KEY (form_id) REFERENCES forms (id),
    ADD CONSTRAINT fk_form_responses_form_version FOREIGN KEY (form_version_id) REFERENCES form_versions (id);

ALTER TABLE matches
    ADD CONSTRAINT fk_matches_blue_one FOREIGN KEY (blue_one) REFERENCES teams (number),
    ADD CONSTRAINT fk_matches_blue_two FOREIGN KEY (blue_two) REFERENCES teams (number),
    ADD CONSTRAINT fk_matches_blue_three FOREIGN KEY (blue_three) REFERENCES teams (number),
    ADD CONSTRAINT fk_matches_red_one FOREIGN KEY (red_one) REFERENCES teams (number),
    ADD CONSTRAINT fk_matches_red_two FOREIGN KEY (red_two) REFERENCES teams (number),
    ADD CONSTRAINT fk_matches_red_three FOREIGN KEY (red_three) REFERENCES teams (number),
    ADD CONSTRAINT fk_matches_event FOREIGN KEY (event_code) REFERENCES events (code);
